### ISSUE TITLE
[Epic] Remove the old network stack

### ISSUE THREAD

**Issue by da-kami** [itchysats/itchysats#2664]
### Maker / Taker Daemon: 

- [x] Remove `maker::connection` module  and all dependencies
    - protocol actors
    - any legacy connection calls in the maker's `cfd` actor (`maker::cfd`)
- [ ] Cleanup taker `cfd` actor (`daemon::taker_cfd`)
    - Remove `maker_identity: Identity`
    - Note: this has a dependency on the model/database changes as the legacy connection identity is currently mandatory when creating `model::Cfd` from an `Order`.
- [x] Remove `daemon::wire` module  and all dependencies
- [x] Remove `daemon::noise`.

### Model / Database

Some of these cleanups might be controversial, but removing some of these `Option`s now that we force the `taker` to connect with a `peer_id` would simplify a lot of things.

- [ ] Cleanup / refactor the `model`
    - `counterparty_peer_id` should be mandatory on `model::Cfd`
         - For `closed` cfds we might not know the `peer_id`, we could still load the legacy id there
    - remove `counterparty_network_identity` from `model::Cfd`
- [ ] Remove `counterparty_network_identity` from the `cfds` table
    - Given that *open* cfds must know a `peer_id` now, we can consider removing this field

## Metrics

Metrics that will need an update on the `ItchySats` board:

- [ ] Offers per minute per taker 
- [ ] Taker environments
    - Note: Currently both `p2p_connections` and `libp2p_connections` is used, this can be cleaned up once we remove the old stack completely
- [ ] Connected takers 
    - Note: Currently both `p2p_connections` and `libp2p_connections` is used, this can be cleaned up once we remove the old stack completely

**Comment by bonomat** [comment]
@klochowicz : afaik you removed the last bits and pieces. Can this be closed now?

**Comment by klochowicz** [comment]
> @klochowicz : afaik you removed the last bits and pieces. Can this be closed now?

not quite, I removed a part of user-facing code-smell (#2909). Things on the list are still present.

**Comment by bonomat** [comment]
This project is unmaintained
