### ISSUE TITLE
Epic: Ready to play

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#72]
We should sort out everything that is between us and sending a download link to someone for trying out the software. This does **not** include features but only infrastructure, shipping etc. We can "play" with the software in an unfinished state. The point of prioritizing this is to avoid surprises after we are "done" that prevent us from trying out the software.

- [x] https://github.com/comit-network/hermes/issues/64
- [x] https://github.com/comit-network/hermes/issues/65
- [x] https://github.com/comit-network/hermes/issues/76
- [x] https://github.com/comit-network/hermes/issues/6
- [x] #94
