### ISSUE TITLE
Epic: Non-collaborative settlement

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#73]
All tasks around providing the backup path of non-collaborative settlement. The oracle plays a key role in this.

- [x] https://github.com/comit-network/hermes/issues/66
- [x] https://github.com/comit-network/hermes/issues/68
- [x] https://github.com/comit-network/hermes/issues/69
- [x] https://github.com/comit-network/hermes/issues/70
- [x] https://github.com/comit-network/hermes/issues/67
- [x] https://github.com/comit-network/hermes/issues/110
- [x] https://github.com/comit-network/hermes/issues/111
- [x] https://github.com/comit-network/hermes/issues/170
- [x] https://github.com/comit-network/hermes/issues/193
