### ISSUE TITLE
Epic: Happy path click-through

### ISSUE THREAD

**Issue by thomaseizinger** [itchysats/itchysats#75]
As a first target, we want to be able to do a full run-through of the happy path:

1. Broker goes online
1. Broker configures their quote in the daemon
1. Trader connects and receives quote
1. Trader accepts quote and they set up a CFD
1. Trader proposes roll-over of contract for another period
1. Trader proposes settlement according to current price
1. Broker accepts settlement and the contract pays out accordingly (on-chain)

---

- [x] https://github.com/comit-network/hermes/issues/3
- [x] https://github.com/comit-network/hermes/issues/62
- [x] https://github.com/comit-network/hermes/issues/60
- [x] https://github.com/comit-network/hermes/issues/33
- [x] https://github.com/comit-network/hermes/issues/5
- [x] #83 
- [x] https://github.com/comit-network/hermes/issues/84
- [x] https://github.com/comit-network/hermes/issues/87
- [x] #96 
- [x] https://github.com/comit-network/hermes/issues/129
- [x] https://github.com/comit-network/hermes/issues/133
- [x] https://github.com/comit-network/hermes/issues/136
- [x] https://github.com/comit-network/hermes/issues/137

**Comment by thomaseizinger** [comment]
Bit too quick @klochowicz :)

**Comment by klochowicz** [comment]
> Bit too quick @klochowicz :)

Does github do it automatically? I haven't clicked anything, but the issue was referenced from the PR...

**Comment by klochowicz** [comment]
> > Bit too quick @klochowicz :)
> 
> Does github do it automatically? I haven't clicked anything, but the issue was referenced from the PR...

sorry, it seems like I referenced the wrong issue! 😅

**Comment by thomaseizinger** [comment]
Removing https://github.com/comit-network/hermes/issues/241 from this epic and consider it done!
